name: QA Brains Playwright Test

on:
  schedule:
    - cron: '0 11 * * *'  # Every day at 7:00 PM PH time

  workflow_dispatch:
    inputs:
      commit_id:
        required: false
        description: The commit SHA triggering this workflow
      commit_message:
        required: false
        description: The commit message
  push:
    branches:
      - main
      - development
      - 'feature-*'
  pull_request:
    branches:
      - main
      - development
      - 'feature-*'

jobs:
  run-playwright:
    uses: ./.github/workflows/run-qa-brains-playwright-test.yml
    with:
      commit_message: ${{ github.event.head_commit.message || github.event.inputs.commit_message || '' }}
      event_type: ${{ github.event_name }}
    secrets: inherit
